//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dmsEntities : DbContext
    {
        public dmsEntities()
            : base("name=dmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<documentstore> documentstores { get; set; }
        public virtual DbSet<semester> semesters { get; set; }
        public virtual DbSet<session> sessions { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<studentrequirement> studentrequirements { get; set; }
    }
}
