//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentrequirement
    {
        public int id { get; set; }
        public int student_id { get; set; }
        public string olevel_type { get; set; }
        public string olevel_result { get; set; }
        public string jamb_type { get; set; }
        public string jamb_de { get; set; }
        public string affidavit { get; set; }
        public string referece_letter { get; set; }
        public string birth_certificate { get; set; }
    }
}
